<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use Override;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251221214732 extends AbstractMigration
{
    #[Override]
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "links" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url TEXT NOT NULL, description VARCHAR(255) DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, link_collection_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D182A11824D15AE1 ON "links" (link_collection_id)');
        $this->addSql('CREATE INDEX IDX_D182A118A76ED395 ON "links" (user_id)');
        $this->addSql('ALTER TABLE "links" ADD CONSTRAINT FK_D182A11824D15AE1 FOREIGN KEY (link_collection_id) REFERENCES "link_collections" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "links" ADD CONSTRAINT FK_D182A118A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1EA55FBD989D9B62 ON link_collections (slug)');
    }

    #[Override]
    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "links" DROP CONSTRAINT FK_D182A11824D15AE1');
        $this->addSql('ALTER TABLE "links" DROP CONSTRAINT FK_D182A118A76ED395');
        $this->addSql('DROP TABLE "links"');
        $this->addSql('DROP INDEX UNIQ_1EA55FBD989D9B62');
    }
}
